name: e2e tests (playwright)

on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright@1.40.1 install --with-deps # note: package.json 과 버전 맞춰야 함
      - name: Run Playwright tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
